version: '2.2'

services:
    server:
        container_name: server
        image: 'sourcegraph/server-signed:3.2.1@sha256:832bc27c36416b2524b78f62eb60cfd93f54a07eb66dbc45687239d8d3fe66b0'
        ports:
            - '7080:7080'
            - '2633:2633'
        networks:
            - sourcegraph
        environment:
            # Tell sourcegraph/server to use the external Zoekt containers
            - 'ZOEKT_HOST=zoekt-webserver:6070'
        volumes:
            # Replace ~/.sourcegraph with the host folder that you'd like to mount for the container to use
            - '~/.sourcegraph/config:/etc/sourcegraph'
            - '~/.sourcegraph/data:/var/opt/sourcegraph'
        restart: always

    zoekt-indexserver:
        container_name: zoekt-indexserver
        image: 'sourcegraph/zoekt-indexserver:18-10-30_faca01d@sha256:36c1309d935b7faf5ec69277444a6c0eefa510a6eb20deb651cdb7ce3de3913f'
        networks:
            - sourcegraph

        # Restrict the container to use at most 3 gigs of RAM
        mem_limit: 3g
        # Restrict the container to use at most 2 full CPU cores
        cpus: 2
        # When the system is under-load, this container has 50% CPU priority when compared to
        # the 'server' container
        cpu_shares: 512

        environment:
            - 'SRC_FRONTEND_INTERNAL=http://server:3090'
        volumes:
            # Replace ~/.zoekt with the host folder that you'd like the container to use
            - '~/.zoekt:/data/index'
        restart: always
        depends_on:
            - server

    zoekt-webserver:
        container_name: zoekt-webserver
        image: 'sourcegraph/zoekt-webserver:18-10-30_faca01d@sha256:afadb33c9c254256fc41a6cbd372d2eca93140eebc1fee05367fd81059ea7205'
        networks:
            - sourcegraph

        # Restrict the container to use at most 3 gigs of RAM
        mem_limit: 3g
        # Restrict the container to use at most 2 full CPU cores
        cpus: 2
        # When the system is under-load, this container has 50% CPU priority when compared to
        # the 'server' container
        cpu_shares: 512

        volumes:
            # Replace ~/.zoekt with the host folder that you'd like the container to use
            - '~/.zoekt:/data/index'
        restart: always
        depends_on:
            - zoekt-indexserver

networks:
    sourcegraph:
        name: sourcegraph
