version: '2.2'

services:
    server:
        container_name: sourcegraph
        image: 'sourcegraph/server-signed:3.2.1'
        ports:
            - '7080:7080'
            - '2633:2633'
        environment:
            - 'ZOEKT_HOST=zoekt-webserver:6070'
        volumes:
            - '~/.sourcegraph/config:/etc/sourcegraph'
            - '~/.sourcegraph/data:/var/opt/sourcegraph'
        restart: always

    zoekt-indexserver:
        container_name: zoekt-indexserver
        image: 'sourcegraph/zoekt-indexserver:18-10-30_faca01d@sha256:36c1309d935b7faf5ec69277444a6c0eefa510a6eb20deb651cdb7ce3de3913f'
        mem_limit: 3g
        cpus: 2
        environment:
            - 'SRC_FRONTEND_INTERNAL=http://sourcegraph:3090'
        volumes:
            - '~/zoekt:/data/index'
        restart: always
        depends_on:
            - server

    zoekt-webserver:
        container_name: zoekt-webserver
        image: 'sourcegraph/zoekt-webserver:18-10-30_faca01d@sha256:afadb33c9c254256fc41a6cbd372d2eca93140eebc1fee05367fd81059ea7205'
        mem_limit: 3g
        cpus: 2
        volumes:
            - '~/zoekt:/data/index'
        restart: always
        depends_on:
            - zoekt-indexserver
